Fix: SC2030, SC2031 - subshell & global vars
The `SC2030` and `SC2031` warnings are due to the script using a
subshell, and trying to modify global variables within the subshell. The
script is using a subshell to run a coprocess in the background, and the
coprocess needs to access the global variables in the `trap` handler for
the `fork()`-ed subshell process.  Note that in this case, the subshell
is not an entirely separate and "fresh" `bash` interpreter, as in
`fork()` + `execve()` in a separate script or separate invocation.

The slightly confusing part here is that some of our functions are
designed to be re-entrant via a separate shell invocation, which is
_launched_ by either `rofi` (relaunched via its plugin API), or by the
`wl-paste --watch` command. The `rofi-lpass` script is designed to be
launched in multiple ways, and in some of these modes it is indeed an
entirely separate co-process.  However, within certain modes, some
functions call subshells which are disowned from the parent shell, and
these subshells are not entirely separate `bash` interpreters because
they have a copy of the shell environment as in `fork()`.

**Note:** There are some subtleties regarding `trap` inheritance and
other behaviors (e.g. `$$` versus `$BASHPID` will return different
values within a subshell, according to POSIX standard and Bash-specific
behavior).

The script within `show-progress-dialog()` was trying to set the global
variables within the subshell, but the shellcheck linter is warning that
the global variables are not being set in the parent shell and therefore
would have different values.

In our case, we don't really care because effectively the subshell is
using these for the `trap` handler, `kill-progress-dialog()`, and the
`tail -f` command is also using the local variable. So we could safely
ignore the shellcheck warnings in this case.  However, it is better to
set the global variables in the parent shell and pass them to the child.
This allows us to ensure that `PROGRESS_FIFO` global variable is set in
the same place where it is created, although we do try to pass it to
most of the various functions that need it as an argument.  This is a
bit of a trade-off between readability and maintainability, and the need
to avoid shellcheck warnings.  In any case, we should try to avoid using
a global variable in this way, except for the special case of `trap`.
This also avoids needing to place `shellcheck` comment directives all
over within the script.

The distictions and nuances between `fork()`-ed subshell(s) and
separated shell process invocations (`fork()` + `execve()`) matter here,
and can be quite esoteric.  In fact, even the venerable [Advanced
Bash-Scripting Guide][1] gets the definition of a subshell slightly
wrong!  This has been the cause of a lot of confusion regarding the
semantics of `()` subshells, global variables, `trap` handlers, and even
the POSIX `$$` shell-PID variable behavior.  Some of these things are
relevant to this script, so I'm adding this discussion here along with
some hopefully helpful references to clear up the details.

References:

  - https://unix.stackexchange.com/a/138498/7688
  - https://stackoverflow.com/a/51903792/645491
  - https://www.shellcheck.net/wiki/SC2030
  - https://www.shellcheck.net/wiki/SC2031

[1]: https://unix.stackexchange.com/q/138463/7688#comment776091_138498

diff --git a/rofi-lpass b/rofi-lpass
--- a/rofi-lpass
+++ b/rofi-lpass
@@ -54,9 +54,10 @@ type-account-field() {
   esac
 }
 
-# Initialize the progress dialog PID to 0
+# Initialize the progress dialog PID to 0, and the FIFO path to an empty string
 # Will be set by return value of show-progress-dialog if SHOW_DIALOG is set
 DIALOG_PID=0
+PROGRESS_FIFO='' # Will be set when we create the FIFO
 
 # kill-progress-dialog will kill the progress dialog and remove the FIFO if they still exist
 # @param dialog_pid PID of the progress dialog
@@ -96,18 +97,26 @@ show-progress-dialog() {
       return 1
     }
 
-    # Both should exit on their own, but return the PIDs just in case
-    # The FIFO write will block unless there is a reader, so we need to run it
+    PROGRESS_FIFO="$progress_fifo"
+
+    # Both should exit on their own, but return the PIDs just in case.
+    # The FIFO write will block unless there is a reader, and yad dialog reader
+    # will stop script execution until it is closed, so we need to run both
     # in the background
     (
       # Close stdout and stderr of this subshell to avoid waiting for any output
       exec 1>/dev/null 2>/dev/null
 
-      # Setup a trap to cleanup the FIFO and temp dir when this subshell coprocess exits
-      # This is a subshell, which didn't inherit the non-exported vars so we
-      # need to set the variable for the trap handler
-      # shellcheck disable=SC2030
-      PROGRESS_FIFO="$progress_fifo"
+      # Setup a trap to cleanup the FIFO and temp dir when this subshell
+      # coprocess exits. This is a subshell, which inherits the non-exported
+      # global vars due to `fork()` so we only need to set the variable above
+      # for the trap handler within this subshell.
+      #
+      # References:
+      #   - https://unix.stackexchange.com/a/138498/7688
+      #   - https://stackoverflow.com/a/51903792/645491
+
+      # Trap on EXIT also to cleanup everything when the subshell exits
       trap 'kill-progress-dialog "$DIALOG_PID"' INT TERM HUP EXIT
 
       tail -f "$progress_fifo" |
@@ -157,20 +166,22 @@ start-watch-clipboard() {
     (
       echo "BEGIN: start-watch-clipboard" >&2
       exec 1>/dev/null 2>/dev/null
-      # Attempt to export the global variables to the subshell, assuming the trap will access these
-      export DIALOG_PID="$DIALOG_PID"
-      export PROGRESS_PID="$PROGRESS_PID"
-      export PROGRESS_FIFO="$PROGRESS_FIFO"
-      # shellcheck disable=SC2064
-      # Eval $DIALOG_PID now, because the subshell will not have it set
-      # We want to cleanup the dialog and FIFO when the wl-paste and thus
-      # subshell fork process is killed
-      trap "kill-progress-dialog '$DIALOG_PID'" INT TERM HUP
-      # wl-paste --watch 'sleep 1; stdbuf -oL echo 100 > $PROGRESS_FIFO'
+      # The non-exported global variables are accessible in the subshell, due to
+      # `fork()`.  The trap will need these.  We want to cleanup the dialog and
+      # FIFO when the `wl-paste` and this subshell fork process is killed. Note
+      # that the code here enclosed within `()` parentheses is a subshell.  Also
+      # note that the `finalize-progress-dialog()` function is called in a
+      # separate shell process (via `fork()` + `execve()`), so we need to pass
+      # these variables in the subshell to be accessible in the
+      # `finalize-progress-dialog()` function's co-process bash interpreter
+      # environment.
+
+      # Trap on EXIT also to cleanup everything when this `wl-paste` subshell exits
+      trap 'kill-progress-dialog "$DIALOG_PID"' INT TERM HUP EXIT
       # finalize-progress-dialog(dialog_pid, progress_pid, progress_fifo, ppid_fifo, pw_cksum)
 
-      # Note: We are re-entrant here, but all global variable state is lost in the new shell,
-      # so we need to pass them as arguments
+      # Note: We are re-entrant here, but all global variable state is lost in
+      # the new shell, so we need to pass them as arguments
       wl-paste --watch "$me" finalize-progress-dialog "$DIALOG_PID" "$PROGRESS_PID" "$PROGRESS_FIFO" "$pw_cksum" 1>&2 2>>/tmp/rofi-lpass-wl-paste-watch.log
     ) &
     self_fork_pid="$!"
